const servicesID = {
  All: -1,
  Uñas: 1,
  Jardineria: 2,
  Barberia: 3,
  Estilismo: 4,
  "Pet Sitting": 5,
  "Lavado de autos": 6,
  Reposteria: 7,
  Plomeria: 8,
  "Servicio electrico ": 9,
  "House Cleaning": 10,
  "Pet Grooming": 11,
  Landscaping: 12,
  "Decorador de eventos": 13,
  DJ: 14,
  Catering: 15,
  Ojaleteria: 16,
  "Diseno grafico": 17,
  Carpinteria: 18,
  "Baby sitting": 19,
  "Mantenimiento de piscina": 20,
  Pintura: 21,
};

export default servicesID;
