const listTowns = {
  Adjuntas: "Adjuntas",
  Aguada: "Aguada",
  Aguadilla: "Aguadilla",
  AguasBuenas: "Aguas Buenas",
  Aibonito: "Aibonito",
  Arecibo: "Arecibo",
  Arroyo: "Arroyo",
  Añasco: "Añasco",
  Barceloneta: "Barceloneta",
  Barranquitas: "Barranquitas",
  Bayamón: "Bayamón",
  CaboRojo: "Cabo Rojo",
  Caguas: "Caguas",
  Camuy: "Camuy",
  Canóvanas: "Canóvanas",
  Carolina: "Carolina",
  Cataño: "Cataño",
  Cayey: "Cayey",
  Ceiba: "Ceiba",
  Ciales: "Ciales",
  Cidra: "Cidra",
  Coamo: "Coamo",
  Comerío: "Comerío",
  Corozal: "Corozal",
  Culebra: "Culebra",
  Dorado: "Dorado",
  Fajardo: "Fajardo",
  Florida: "Florida",
  Guayama: "Guayama",
  Guayanilla: "Guayanilla",
  Guaynabo: "Guaynabo",
  Gurabo: "Gurabo",
  Guánica: "Guánica",
  Hatillo: "Hatillo",
  Hormigueros: "Hormigueros",
  Humacao: "Humacao",
  Isabela: "Isabela",
  Jayuya: "Jayuya",
  JuanaDíaz: "Juana Díaz",
  Juncos: "Juncos",
  Lajas: "Lajas",
  Lares: "Lares",
  LasMarías: "Las Marías",
  LasPiedras: "Las Piedras",
  Loiza: "Loiza",
  Luquillo: "Luquillo",
  Manatí: "Manatí",
  Maricao: "Maricao",
  Maunabo: "Maunabo",
  Mayagüez: "Mayagüez",
  Moca: "Moca",
  Morovis: "Morovis",
  Naguabo: "Naguabo",
  Naranjito: "Naranjito",
  Orocovis: "Orocovis",
  Patillas: "Patillas",
  Peñuelas: "Peñuelas",
  Ponce: "Ponce",
  Quebradillas: "Quebradillas",
  Rincón: "Rincón",
  RioGrande: "Rio Grande",
  SabanaGrande: "Sabana Grande",
  Salinas: "Salinas",
  SanGermán: "San Germán",
  SanJuan: "San Juan",
  SanLorenzo: "San Lorenzo",
  SanSebastián: "San Sebastián",
  SantaIsabel: "Santa Isabel",
  ToaAlta: "Toa Alta",
  ToaBaja: "Toa Baja",
  TrujilloAlto: "Trujillo Alto",
  Utuado: "Utuado",
  VegaAlta: "Vega Alta",
  VegaBaja: "Vega Baja",
  Vieques: "Vieques",
  Villalba: "Villalba",
  Yabucoa: "Yabucoa",
  Yauco: "Yauco",
};

export default listTowns;
