-- Allow visibility for user on tables
REVOKE CONNECT ON DATABASE demo_db FROM PUBLIC;

GRANT CONNECT
ON DATABASE demo_db
TO pepe;

REVOKE ALL
ON ALL TABLES IN SCHEMA public 
FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA public 
TO pepe;
